// Generated by CoffeeScript 1.7.1
(function() {
  var Chatroom, http, options, random_word_url;

  random_word_url = 'randomword.setgetgo.com';

  http = require('http');

  options = {
    host: random_word_url,
    port: 80,
    path: '/get.php'
  };

  Chatroom = (function() {
    Chatroom.rooms = {};

    function Chatroom(name, password) {
      if ((password == null) || (name == null)) {
        this.name = name;
        this.password = password;
        this.status = {
          valid: true
        };
        console.log('New Chatroom made');
      } else {
        this.status = {
          valid: false,
          reason: 'A Room Must have a Password and Name.'
        };
      }
      if (Chatroom.rooms[room.name] != null) {
        this.status = {
          valid: false,
          reason: 'There is already a room with this name.'
        };
      }
    }

    Chatroom.new_chatroom = function(name) {
      var password;
      password = '';
      return [1, 2, 3].forEach(function(i) {
        return http.get(options, function(resp) {
          resp.on('data', function(chunk) {
            console.log('BODY: ' + chunk);
            return password += chunk;
          });
          return resp.on('end', function() {
            var room;
            if (i === 3) {
              room = new Chatroom(name, password);
              if (room.status.valid === true) {
                Chatroom.rooms[room.name] = room;
                console.log(room.status.reason);
              } else {

              }
              return room;
            }
          });
        });
      });
    };

    return Chatroom;

  })();

  exports.Chatroom = Chatroom;

}).call(this);
