// Generated by CoffeeScript 1.7.1
(function() {
  var app, cs, http, io;

  cs = require('coffee-script/register');

  app = require('express')();

  http = require('http').Server(app);

  io = require('socket.io')(http);

  app.get('/', function(req, res) {
    return res.sendfile('assets/html/index.html');
  });

  app.get('/application.js', function(req, res) {
    return res.sendfile('assets/javascript/application.js');
  });

  io.on('connection', function(socket) {
    console.log('a user connected');
    socket.on('disconnect', function() {
      return console.log('user disconnected');
    });
    return socket.on('chat message', function(msg) {
      console.log('message: ' + msg);
      return io.emit('receive-chat', {
        message: msg,
        "for": 'everyone'
      });
    });
  });

  http.listen(3000, function() {
    return console.log('listening on *:3000');
  });

}).call(this);
